"""Authoritative Power & Utilities system decomposition (modules) + extra use cases.

Hand-authored, domain-accurate catalog that REPLACES the keyword-derived asset
list. Taxonomy: each source_category is a deployed platform/system; modules are
the vendor-neutral capabilities/subsystems within it. ADMS is the integrated
DISTRIBUTION platform; EMS the integrated TRANSMISSION platform; standalone
SCADA/OMS are represented as their own thin categories so utilities that run
them separately map cleanly. `domain` (owning LOB) disambiguates capabilities
that appear in both (e.g. SCADA under EMS=Transmission vs ADMS=Distribution).

Each module: (source_category, module, keywords, sub_vertical, owning_domain, effort)
  keywords -> match the parent-catalog's free-text dataRequirements so the 198
  imported use cases still resolve their required data. New use cases below use
  EXPLICIT (category, module) requires — no keyword guessing.
"""

# ---------------------------------------------------------------------------
# MODULE CATALOG  (source_category, module, keywords, sub_vertical, domain, effort)
# ---------------------------------------------------------------------------
MODULES = [
    # ===== ERP (utilities) =====
    ("ERP", "Plant Maintenance / EAM", ["work order", "maintenance record", "equipment master", "cmms", "notification", "eam", "plant maintenance"], "cross", "Corporate Services", "M"),
    ("ERP", "Materials Management", ["inventory", "spare part", "materials", "vendor master", "goods movement"], "cross", "Corporate Services", "M"),
    ("ERP", "Finance & Controlling", ["financial", "cost center", "ledger", "actuals", "revenue", "gl ", "controlling"], "cross", "Corporate Services", "M"),
    ("ERP", "Asset Accounting", ["asset accounting", "depreciation", "fixed asset", "book value"], "cross", "Corporate Services", "S"),
    ("ERP", "Project System", ["project", "wbs", "capital project", "outage project"], "cross", "Corporate Services", "M"),
    ("ERP", "Human Capital Management", ["workforce", "employee", "headcount", "certification", "timesheet", "labor", "retirement", "payroll"], "cross", "Corporate Services", "M"),
    ("ERP", "Procurement / Sourcing", ["procurement", "purchase order", "sourcing", "supplier"], "cross", "Corporate Services", "S"),
    ("ERP", "Quality Management", ["inspection lot", "quality notification", "supplier quality"], "cross", "Corporate Services", "S"),
    ("ERP", "Inventory / Warehouse", ["warehouse", "storeroom", "stock", "inventory management"], "cross", "Corporate Services", "S"),
    ("ERP", "Environment, Health & Safety", ["ehs", "incident", "osha", "safety observation", "near miss"], "cross", "Corporate Services", "M"),
    ("ERP", "Work Clearance Management", ["lockout", "tagout", "work clearance", "safety permit", "loto"], "cross", "Corporate Services", "S"),

    # ===== EAM / APM (asset & work management) =====
    ("EAM/APM", "Asset Registry & Hierarchy", ["asset registry", "asset hierarchy", "asset master"], "cross", "Corporate Services", "M"),
    ("EAM/APM", "Work Order Management", ["work order", "corrective maintenance", "job execution"], "cross", "Corporate Services", "M"),
    ("EAM/APM", "Preventive Maintenance Scheduling", ["preventive maintenance", "pm schedule", "maintenance trigger"], "cross", "Corporate Services", "M"),
    ("EAM/APM", "Condition Monitoring / PdM", ["condition monitoring", "predictive maintenance", "sensor health", "pdm"], "cross", "Corporate Services", "L"),
    ("EAM/APM", "Reliability / RCM", ["reliability", "rcm", "failure mode", "reliability-centered"], "cross", "Corporate Services", "M"),
    ("EAM/APM", "Asset Performance & Health Scoring", ["asset health", "criticality", "apm", "health score", "reliability strategy"], "cross", "Corporate Services", "L"),
    ("EAM/APM", "Reliability Library / Failure Modes", ["epri", "failure mode", "reliability data", "preventive maintenance template"], "cross", "Corporate Services", "S"),
    ("EAM/APM", "Spare Parts / Inventory", ["spare part", "storeroom", "parts availability"], "cross", "Corporate Services", "S"),
    ("EAM/APM", "Mobile Workforce Management", ["mobile workforce", "field technician", "crew mobile"], "cross", "Corporate Services", "M"),
    ("EAM/APM", "Inspection / Rounds", ["inspection", "operator rounds", "field data collection"], "cross", "Corporate Services", "S"),
    ("EAM/APM", "Failure Analysis / RCA", ["root cause", "rca", "defect elimination", "failure analysis"], "cross", "Corporate Services", "M"),
    ("EAM/APM", "Vibration / Condition Routes", ["vibration", "machinery vibration", "rotating equipment", "condition route"], "cross", "Corporate Services", "M"),
    ("EAM/APM", "Scheduling & Crew Optimization", ["scheduling", "crew optimization", "labor scheduling", "resource leveling"], "cross", "Corporate Services", "M"),
    ("EAM/APM", "Calibration Management", ["calibration", "instrument calibration"], "cross", "Corporate Services", "S"),

    # ===== Data Historian (OT process data) — fossil/thermal =====
    ("Data Historian", "Steam Turbine", ["turbine", "bearing vibration", "casing temp", "thrust", "valve position"], "fossil", "Generation", "L"),
    ("Data Historian", "Generator / Excitation", ["generator", "stator", "rotor", "excitation", "hydrogen purity", "mvar"], "fossil", "Generation", "L"),
    ("Data Historian", "Boiler / HRSG", ["boiler", "hrsg", "superheater", "drum level", "steam temp"], "fossil", "Generation", "L"),
    ("Data Historian", "Feedwater / Condensate", ["feedwater", "condensate", "heater level", "feed pump"], "fossil", "Generation", "M"),
    ("Data Historian", "Combustion / Burner Management", ["combustion", "burner", "flame", "fuel/air", "combustion dynamics", "emissions tuning", "event frame", "proficy"], "fossil", "Generation", "M"),
    ("Data Historian", "Balance of Plant", ["balance of plant", "bop", "auxiliaries", "cooling water"], "cross", "Generation", "M"),
    ("Data Historian", "Emissions Process Tags", ["stack tag", "emissions process", "nox process", "opacity tag"], "fossil", "Generation", "S"),
    ("Data Historian", "Vibration / Condition Monitoring", ["online vibration", "machine health", "bearing health"], "cross", "Generation", "M"),
    # renewable / hydro
    ("Data Historian", "Wind Turbine", ["wind turbine", "gearbox", "pitch", "yaw", "nacelle", "power curve"], "renewables", "Generation", "L"),
    ("Data Historian", "Solar Inverter / PV", ["solar", "inverter", "pv string", "irradiance"], "renewables", "Generation", "M"),
    ("Data Historian", "Hydro Unit", ["hydro", "wicket gate", "head", "unit mw", "governor"], "hydro", "Generation", "M"),
    # nuclear-specific
    ("Data Historian", "Reactor Coolant System", ["reactor coolant", "rcs", "primary loop", "primary temp"], "nuclear", "Generation", "L"),
    ("Data Historian", "Reactor Core / Neutronics", ["neutron flux", "reactivity", "control rod", "neutronics", "core"], "nuclear", "Generation", "L"),
    ("Data Historian", "Steam Generator / Secondary", ["steam generator", "sg level", "secondary loop"], "nuclear", "Generation", "M"),
    ("Data Historian", "Pressurizer", ["pressurizer", "pressure control", "level control"], "nuclear", "Generation", "S"),
    ("Data Historian", "Containment", ["containment", "sump level", "containment pressure"], "nuclear", "Generation", "M"),
    ("Data Historian", "Safety Systems (ECCS/RHR)", ["eccs", "rhr", "safety system", "emergency core cooling", "residual heat"], "nuclear", "Generation", "L"),

    # ===== EMS (transmission platform) =====
    ("EMS (Transmission)", "T-SCADA", ["scada", "substation telemetry", "supervisory control", "real-time telemetry"], "cross", "Transmission", "L"),
    ("EMS (Transmission)", "Network Topology Processor", ["topology processor", "bus-branch", "switch status"], "cross", "Transmission", "M"),
    ("EMS (Transmission)", "State Estimation", ["state estimator", "state estimation", "network state"], "cross", "Transmission", "L"),
    ("EMS (Transmission)", "Real-Time Contingency Analysis", ["rtca", "contingency analysis", "n-1", "security assessment"], "cross", "Transmission", "L"),
    ("EMS (Transmission)", "AGC / LFC", ["agc", "automatic generation control", "regulation", "setpoint", "load-frequency", "lfc"], "cross", "Transmission", "M"),
    ("EMS (Transmission)", "Economic Dispatch", ["economic dispatch", "least-cost dispatch"], "cross", "Transmission", "M"),
    ("EMS (Transmission)", "Unit Commitment", ["unit commitment", "generator start/stop", "commitment schedule"], "cross", "Transmission", "M"),
    ("EMS (Transmission)", "Optimal Power Flow", ["optimal power flow", "opf", "constrained dispatch"], "cross", "Transmission", "L"),
    ("EMS (Transmission)", "Voltage / VAR Scheduling", ["voltage schedule", "var scheduling", "reactive dispatch"], "cross", "Transmission", "M"),
    ("EMS (Transmission)", "Load Forecasting", ["load forecast", "demand forecast", "system demand"], "cross", "Transmission", "M"),
    ("EMS (Transmission)", "Interchange Scheduling", ["interchange", "tie-line schedule", "transaction schedule"], "cross", "Transmission", "M"),
    ("EMS (Transmission)", "Network Model / CIM", ["cim", "network model", "model exchange"], "cross", "Transmission", "M"),
    ("EMS (Transmission)", "Disturbance / SOE Analysis", ["sequence of events", "soe", "disturbance analysis", "event review"], "cross", "Transmission", "S"),

    # ===== ADMS (distribution platform) =====
    ("ADMS (Distribution)", "D-SCADA", ["distribution scada", "d-scada", "feeder telemetry"], "cross", "Distribution", "L"),
    ("ADMS (Distribution)", "OMS (Outage Management)", ["oms", "outage", "restoration", "interruption", "saidi", "saifi", "crew status", "trouble call"], "cross", "Distribution", "L"),
    ("ADMS (Distribution)", "DMS (Distribution Management)", ["dms", "distribution management", "network operations"], "cross", "Distribution", "L"),
    ("ADMS (Distribution)", "Distribution Power Flow", ["distribution power flow", "dpf", "unbalanced load flow", "three-phase"], "cross", "Distribution", "M"),
    ("ADMS (Distribution)", "FLISR", ["flisr", "fault location isolation", "self-healing", "sectionalizing", "reconfiguration"], "cross", "Distribution", "L"),
    ("ADMS (Distribution)", "VVO / CVR", ["volt/var", "vvo", "cvr", "conservation voltage", "voltage optimization"], "cross", "Distribution", "M"),
    ("ADMS (Distribution)", "Fault Location Analysis", ["fault location", "fla", "fault position", "feeder fault"], "cross", "Distribution", "M"),
    ("ADMS (Distribution)", "Distribution State Estimation", ["distribution state estimation", "feeder state"], "cross", "Distribution", "M"),
    ("ADMS (Distribution)", "Distribution Load Forecasting", ["feeder load forecast", "der load", "short-term feeder"], "cross", "Distribution", "M"),
    ("ADMS (Distribution)", "Switching Sequence Management", ["switching sequence", "ssm", "switching order"], "cross", "Distribution", "S"),
    ("ADMS (Distribution)", "Storm / Damage Assessment", ["storm", "damage assessment", "major event", "restoration resource"], "cross", "Distribution", "M"),

    # ===== Standalone SCADA / OMS (utilities that run them separately) =====
    ("Standalone SCADA", "Real-Time Telemetry & Control", ["standalone scada", "rtu", "telemetry", "supervisory"], "cross", "Transmission", "M"),
    ("Standalone OMS", "Outage Events & Restoration", ["standalone oms", "outage events", "restoration mgmt"], "cross", "Distribution", "M"),

    # ===== DERMS =====
    ("DERMS", "DER Registration & Modeling", ["der registration", "der model", "distributed energy resource"], "renewables", "Distribution", "M"),
    ("DERMS", "DER Dispatch & Control", ["derms", "der dispatch", "aggregation", "setpoint control", "battery", "storage"], "renewables", "Distribution", "M"),
    ("DERMS", "EV Charging Management", ["ev charging", "electric vehicle", "managed charging"], "renewables", "Distribution", "M"),
    ("DERMS", "Demand Response / Load Control", ["demand response", "load control", "demand-side", "energy efficiency program", "curtailment device"], "cross", "Customer", "M"),
    ("DERMS", "Virtual Power Plant Orchestration", ["virtual power plant", "vpp", "der aggregation dispatch"], "renewables", "Distribution", "L"),

    # ===== GIS =====
    ("GIS", "Electric Network Model / Connectivity", ["gis", "network model", "connectivity", "topology", "electrical model", "tracing"], "cross", "Distribution", "M"),
    ("GIS", "Utility Network (ArcGIS)", ["utility network", "arcgis utility", "association model"], "cross", "Distribution", "M"),
    ("GIS", "Asset Inventory (Spatial)", ["asset location", "spatial asset", "feature class", "asset inventory"], "cross", "Distribution", "S"),
    ("GIS", "Staking / Design", ["staking", "distribution design", "construction design", "work design"], "cross", "Distribution", "S"),
    ("GIS", "Vegetation Management", ["vegetation", "right-of-way", "tree", "encroachment", "lidar", "satellite", "imagery"], "cross", "Distribution", "M"),
    ("GIS", "Mobile GIS / Field Maps", ["mobile gis", "field maps", "redlining"], "cross", "Distribution", "S"),

    # ===== Meter / AMI / MDM =====
    ("Meter/AMI/MDM", "Head-End System", ["hes", "head-end", "meter communication"], "cross", "Customer", "M"),
    ("Meter/AMI/MDM", "Interval Usage Collection", ["ami", "smart meter", "interval data", "meter read", "consumption", "interval usage"], "cross", "Customer", "L"),
    ("Meter/AMI/MDM", "Meter Events / Alarms", ["meter event", "tamper", "meter alarm", "last gasp"], "cross", "Customer", "S"),
    ("Meter/AMI/MDM", "Voltage / VAR Telemetry", ["meter voltage", "power quality meter", "voltage telemetry"], "cross", "Customer", "M"),
    ("Meter/AMI/MDM", "MDM Repository", ["mdm", "meter data management", "meter data store"], "cross", "Customer", "M"),
    ("Meter/AMI/MDM", "VEE (Validation/Estimation/Editing)", ["vee", "validation estimation editing", "data quality meter", "gap fill"], "cross", "Customer", "M"),
    ("Meter/AMI/MDM", "Load Profiles", ["load profile", "usage shape"], "cross", "Customer", "S"),
    ("Meter/AMI/MDM", "Remote Disconnect / Reconnect", ["disconnect", "reconnect", "remote service switch"], "cross", "Customer", "S"),

    # ===== CIS / Billing =====
    ("CIS/Billing", "Customer Accounts", ["customer account", "premise record", "account management"], "cross", "Customer", "M"),
    ("CIS/Billing", "Billing Engine / Determinants", ["billing", "billing determinant", "charge calculation", "meter-to-cash", "is-u", "utilities billing"], "cross", "Customer", "M"),
    ("CIS/Billing", "Rate Schedules / Tariffs", ["rate schedule", "tariff", "pricing rule"], "cross", "Customer", "S"),
    ("CIS/Billing", "Payments / Collections", ["payment", "collections", "arrears", "dunning", "bad debt", "remittance"], "cross", "Customer", "M"),
    ("CIS/Billing", "CRM / Contact Center", ["crm", "call", "contact center", "customer preference", "demographic", "churn", "case management"], "cross", "Customer", "M"),
    ("CIS/Billing", "Service Orders / Field Service", ["service order", "field service", "connect disconnect"], "cross", "Customer", "S"),
    ("CIS/Billing", "Revenue Protection / Theft", ["revenue protection", "theft", "non-technical loss", "energy theft"], "cross", "Customer", "M"),
    ("CIS/Billing", "Programs / DSM Enrollment", ["rebate", "program enrollment", "dsm", "energy program"], "cross", "Customer", "S"),

    # ===== Market / ISO feeds =====
    ("Market/ISO Feed", "Day-Ahead LMP", ["day-ahead", "dam", "day ahead lmp"], "cross", "Generation", "S"),
    ("Market/ISO Feed", "Real-Time LMP", ["real-time market", "real-time lmp", "rtm", "5-minute price", "nodal"], "cross", "Generation", "S"),
    ("Market/ISO Feed", "LMP Components (Energy/Congestion/Loss)", ["lmp component", "congestion price", "loss component", "energy component"], "cross", "Generation", "S"),
    ("Market/ISO Feed", "Bids & Offers", ["bid", "offer", "market offer", "generation offer"], "cross", "Generation", "M"),
    ("Market/ISO Feed", "Virtual Bids (INC/DEC)", ["virtual bid", "inc", "dec", "financial bid"], "cross", "Generation", "M"),
    ("Market/ISO Feed", "Ancillary Services", ["ancillary", "regulation reserve", "spinning reserve", "frequency response", "ordc"], "cross", "Generation", "M"),
    ("Market/ISO Feed", "Capacity Market", ["capacity market", "rpm", "capacity auction", "fcm"], "cross", "Generation", "M"),
    ("Market/ISO Feed", "Settlements / Invoicing", ["settlement", "invoice", "settlement statement", "charge determination"], "cross", "Generation", "M"),
    ("Market/ISO Feed", "FTR / CRR", ["ftr", "crr", "congestion revenue", "transmission rights"], "cross", "Generation", "M"),
    ("Market/ISO Feed", "Congestion / Constraints", ["binding constraint", "shadow price", "congestion", "transmission constraint"], "cross", "Generation", "S"),
    ("Market/ISO Feed", "Interchange / Tie Schedules", ["interchange schedule", "tie schedule", "position management"], "cross", "Generation", "S"),
    ("Market/ISO Feed", "ISO Load & Gen Forecast", ["iso forecast", "market rules", "demand forecast feed", "flexible ramp", "oasis", "curtailment"], "cross", "Generation", "S"),

    # ===== PMU / Synchrophasor (WAMS) =====
    ("PMU/Synchrophasor", "Phasor Measurement", ["synchrophasor", "pmu", "phasor", "phasor measurement"], "cross", "Transmission", "M"),
    ("PMU/Synchrophasor", "Phasor Data Concentrator", ["pdc", "phasor concentrator", "time-align"], "cross", "Transmission", "S"),
    ("PMU/Synchrophasor", "Oscillation Detection", ["oscillation", "damping", "low-frequency mode", "stability"], "cross", "Transmission", "M"),
    ("PMU/Synchrophasor", "Linear State Measurement", ["linear state estimation", "phasor state"], "cross", "Transmission", "M"),
    ("PMU/Synchrophasor", "Islanding / Angle Separation", ["islanding", "angle separation", "loss of synchronism"], "cross", "Transmission", "M"),

    # ===== CEMS =====
    ("CEMS", "Gas Analyzers (NOx/SO2/CO2/O2)", ["cems", "nox", "so2", "co2", "gas analyzer", "emission"], "fossil", "Regulatory", "S"),
    ("CEMS", "Opacity / Particulate", ["opacity", "particulate", "coms"], "fossil", "Regulatory", "S"),
    ("CEMS", "Stack Flow", ["stack flow", "volumetric flow", "exhaust flow"], "fossil", "Regulatory", "S"),
    ("CEMS", "DAHS (Data Acquisition)", ["dahs", "emissions data", "data acquisition handling"], "fossil", "Regulatory", "M"),
    ("CEMS", "Part 75 Reporting / EDR", ["part 75", "edr", "emissions reporting", "epa report"], "fossil", "Regulatory", "S"),
    ("CEMS", "QA/QC (RATA/Calibration)", ["rata", "calibration audit", "emissions qa"], "fossil", "Regulatory", "S"),

    # ===== LIMS =====
    ("LIMS", "Sample Management", ["sample management", "chain of custody", "sample login", "lims"], "cross", "Generation", "S"),
    ("LIMS", "Water / Fuel Chemistry", ["water chemistry", "fuel chemistry", "chemistry test", "lab"], "cross", "Generation", "M"),
    ("LIMS", "Results Management", ["test result", "analytical result", "result capture"], "cross", "Generation", "S"),
    ("LIMS", "QA/QC / Control Charts", ["control chart", "lab qa", "quality control chemistry"], "cross", "Generation", "S"),

    # ===== Dosimetry / Radiation Protection (nuclear) =====
    ("Radiation/Dosimetry", "Personnel Dosimetry", ["dosimetry", "personnel dose", "tld", "epd", "cumulative dose"], "nuclear", "Generation", "M"),
    ("Radiation/Dosimetry", "RWP / Access Control", ["rwp", "radiation work permit", "access control"], "nuclear", "Generation", "S"),
    ("Radiation/Dosimetry", "Area Radiation Monitors", ["area radiation monitor", "arm", "dose rate", "area monitor"], "nuclear", "Regulatory", "M"),
    ("Radiation/Dosimetry", "Effluent Monitoring", ["effluent", "gaseous effluent", "liquid effluent", "radioactive release"], "nuclear", "Regulatory", "M"),
    ("Radiation/Dosimetry", "Contamination / Survey", ["contamination survey", "survey data", "contamination map"], "nuclear", "Generation", "S"),
    ("Radiation/Dosimetry", "ALARA Planning", ["alara", "dose minimization", "collective dose"], "nuclear", "Generation", "M"),

    # ===== Document / Content Management =====
    ("Document/Content Mgmt", "Procedures Management", ["procedure", "operating procedure", "procedure qualification"], "cross", "Regulatory", "S"),
    ("Document/Content Mgmt", "Engineering Drawings / CAD", ["engineering drawing", "cad", "drawing revision"], "cross", "Regulatory", "S"),
    ("Document/Content Mgmt", "Regulatory Document Mgmt", ["nrc", "regulatory document", "license basis", "inspection report", "generic letter", "bulletin", "ferc"], "nuclear", "Regulatory", "M"),
    ("Document/Content Mgmt", "Records Management / Retention", ["records management", "retention", "quality record"], "cross", "Regulatory", "S"),
    ("Document/Content Mgmt", "Commitment Tracking", ["commitment tracking", "regulatory correspondence", "regulatory commitment", "rate case", "filing", "tariff", "allowed return", "penalty"], "cross", "Regulatory", "M"),

    # ===== Fuel Management =====
    ("Fuel Management", "Fossil Fuel Inventory", ["fuel schedule", "coal", "fuel inventory", "fuel availability", "oil"], "fossil", "Generation", "S"),
    ("Fuel Management", "Fuel Contracts / Procurement", ["fuel contract", "fuel procurement", "supply agreement"], "fossil", "Generation", "S"),
    ("Fuel Management", "Gas Nominations", ["gas nomination", "pipeline nomination", "gas scheduling", "balancing"], "fossil", "Generation", "M"),
    ("Fuel Management", "Fuel Quality / Blending", ["fuel quality", "heat content", "fuel blending"], "fossil", "Generation", "S"),
    ("Fuel Management", "Nuclear Fuel Cycle", ["fuel assembly", "burnup", "enrichment", "fuel cycle", "fabrication"], "nuclear", "Generation", "M"),
    ("Fuel Management", "Core Design / Reload", ["core design", "core load", "reload", "depletion"], "nuclear", "Generation", "L"),
    ("Fuel Management", "Spent Fuel Management", ["spent fuel", "dry cask", "used fuel pool"], "nuclear", "Generation", "M"),

    # ===== Weather =====
    ("Weather", "NWP Forecasts", ["noaa", "hrrr", "gfs", "numerical weather", "weather grid", "nwp"], "renewables", "Generation", "S"),
    ("Weather", "Site-Specific Forecasts", ["dtn", "site weather", "site forecast"], "renewables", "Generation", "S"),
    ("Weather", "Lightning Detection", ["lightning", "strike density"], "cross", "Distribution", "S"),
    ("Weather", "Storm / Severe Weather Tracking", ["storm track", "storm feed", "severe weather"], "cross", "Distribution", "S"),
    ("Weather", "Renewable Generation Forecasting", ["wind forecast", "solar forecast", "irradiance forecast", "generation forecast weather"], "renewables", "Generation", "M"),
    ("Weather", "Icing / Wind Loading", ["icing", "wind loading", "line loading environmental"], "cross", "Transmission", "S"),
]

# ---------------------------------------------------------------------------
# EXTRA USE CASES (appended to the parent-derived 198). Each:
#  dict(id, title, description, domain, sub_vertical, effort, win_rate,
#       compliance[], risk_tags[], value_components[], time_to_value,
#       requires=[(category, module, 'required'|'helpful')],
#       enables=[parent_id or new id])
# value_components: [{name, calculationDisplay, multiplier, assumptionKeys[], lowCoeff, highCoeff}]
# ---------------------------------------------------------------------------
def _c(name, disp, mult, keys, lo=0.7, hi=1.3):
    return {"name": name, "calculationDisplay": disp, "multiplier": mult,
            "assumptionKeys": keys, "lowCoeff": lo, "highCoeff": hi}


EXTRA_USE_CASES = [
    dict(id="x_gen_hrsg_life", title="HRSG Life & Creep-Fatigue Analytics",
         description="Predict HRSG tube creep/fatigue damage from historian thermal-cycle data to avoid forced outages on combined-cycle units.",
         domain="Generation", sub_vertical="fossil", effort="L", win_rate=0.55, time_to_value="6–10 months",
         compliance=["NERC"], risk_tags=["tube failure", "forced outage"],
         value_components=[_c("Avoided forced-outage cost", "generation fleet × capacity price × 365 ÷ 1M × 0.2%", 7.3e-7, ["generationFleetMW", "capacityPriceMWDay"])],
         requires=[("Data Historian", "Boiler / HRSG", "required"), ("Data Historian", "Combustion / Burner Management", "helpful"), ("EAM/APM", "Condition Monitoring / PdM", "required")],
         enables=[]),
    dict(id="x_gen_turbine_dt", title="Steam Turbine Digital Twin",
         description="Physics + ML digital twin of the steam turbine for heat-rate and remaining-life optimization.",
         domain="Generation", sub_vertical="fossil", effort="XL", win_rate=0.48, time_to_value="12–18 months",
         compliance=["NERC"], risk_tags=["equipment failure", "efficiency loss"],
         value_components=[_c("Heat-rate improvement", "annual fuel × 1% heat-rate", 0.01, ["annualFuelSpendMM"])],
         requires=[("Data Historian", "Steam Turbine", "required"), ("Data Historian", "Generator / Excitation", "required"), ("EAM/APM", "Condition Monitoring / PdM", "helpful")],
         enables=[]),
    dict(id="x_gen_generator_pdm", title="Generator Excitation & Winding PdM",
         description="Predict generator stator/rotor and excitation degradation from historian tags.",
         domain="Generation", sub_vertical="fossil", effort="L", win_rate=0.58, time_to_value="6–9 months",
         compliance=["NERC"], risk_tags=["equipment failure"],
         value_components=[_c("Avoided generator failure", "generation fleet × capacity price × 365 ÷ 1M × 0.15%", 5.5e-7, ["generationFleetMW", "capacityPriceMWDay"])],
         requires=[("Data Historian", "Generator / Excitation", "required"), ("EAM/APM", "Condition Monitoring / PdM", "required")],
         enables=["x_gen_turbine_dt"]),
    dict(id="x_nuc_reactor_perf", title="Reactor Performance & Anomaly Monitoring",
         description="Continuous RCS/core anomaly detection to reduce unplanned scrams.",
         domain="Generation", sub_vertical="nuclear", effort="XL", win_rate=0.5, time_to_value="12–24 months",
         compliance=["NRC"], risk_tags=["safety", "reactor trip"],
         value_components=[_c("Avoided scram cost", "generation fleet × capacity price × 365 ÷ 1M × 0.25%", 9.1e-7, ["generationFleetMW", "capacityPriceMWDay"])],
         requires=[("Data Historian", "Reactor Coolant System", "required"), ("Data Historian", "Reactor Core / Neutronics", "required"), ("Data Historian", "Steam Generator / Secondary", "helpful")],
         enables=["x_nuc_refuel_opt", "x_nuc_cbm"]),
    dict(id="x_nuc_refuel_opt", title="Refueling-Outage Critical-Path Optimization",
         description="Sequence refueling-outage work (EAM + core reload) to cut critical-path days.",
         domain="Generation", sub_vertical="nuclear", effort="L", win_rate=0.52, time_to_value="9–15 months",
         compliance=["NRC"], risk_tags=["schedule overrun"],
         value_components=[_c("Outage duration reduction", "O&M budget × 0.4%", 0.004, ["omBudgetMM"])],
         requires=[("EAM/APM", "Scheduling & Crew Optimization", "required"), ("ERP", "Project System", "required"), ("Fuel Management", "Core Design / Reload", "required")],
         enables=[]),
    dict(id="x_nuc_cbm", title="Nuclear Equipment Reliability / CBM",
         description="Condition-based maintenance for safety-related nuclear equipment.",
         domain="Generation", sub_vertical="nuclear", effort="L", win_rate=0.54, time_to_value="9–12 months",
         compliance=["NRC"], risk_tags=["equipment failure", "safety"],
         value_components=[_c("Corrective-maintenance reduction", "O&M budget × 0.3%", 0.003, ["omBudgetMM"])],
         requires=[("EAM/APM", "Reliability / RCM", "required"), ("EAM/APM", "Condition Monitoring / PdM", "required"), ("Data Historian", "Safety Systems (ECCS/RHR)", "helpful")],
         enables=[]),
    dict(id="x_nuc_alara", title="Dosimetry & ALARA Analytics",
         description="Analyze personnel dose and area/effluent monitors to drive ALARA.",
         domain="Generation", sub_vertical="nuclear", effort="M", win_rate=0.6, time_to_value="4–8 months",
         compliance=["NRC"], risk_tags=["radiation exposure"],
         value_components=[_c("Collective-dose / rework reduction", "O&M budget × 0.1%", 0.001, ["omBudgetMM"])],
         requires=[("Radiation/Dosimetry", "Personnel Dosimetry", "required"), ("Radiation/Dosimetry", "Area Radiation Monitors", "helpful"), ("Radiation/Dosimetry", "ALARA Planning", "required")],
         enables=[]),
    dict(id="x_nuc_effluent", title="Radioactive Effluent Trend & Reporting",
         description="Trend gaseous/liquid effluent vs limits with automated NRC/EPA reporting.",
         domain="Regulatory", sub_vertical="nuclear", effort="M", win_rate=0.56, time_to_value="4–6 months",
         compliance=["NRC", "EPA"], risk_tags=["compliance gap"],
         value_components=[_c("Reporting-effort reduction", "O&M budget × 0.05%", 0.0005, ["omBudgetMM"])],
         requires=[("Radiation/Dosimetry", "Effluent Monitoring", "required"), ("LIMS", "Water / Fuel Chemistry", "helpful")],
         enables=[]),
    dict(id="x_gen_renew_forecast", title="Wind & Solar Generation Forecasting",
         description="Short-term renewable output forecasting from historian + weather to cut imbalance.",
         domain="Generation", sub_vertical="renewables", effort="M", win_rate=0.62, time_to_value="4–8 months",
         compliance=[], risk_tags=["forecast error", "curtailment"],
         value_components=[_c("Imbalance-penalty reduction", "generation fleet × capacity price × 365 ÷ 1M × 0.2%", 7.3e-7, ["generationFleetMW", "capacityPriceMWDay"])],
         requires=[("Data Historian", "Wind Turbine", "required"), ("Data Historian", "Solar Inverter / PV", "required"), ("Weather", "Renewable Generation Forecasting", "required"), ("Weather", "NWP Forecasts", "helpful")],
         enables=["x_mkt_bidding"]),
    dict(id="x_gen_wind_pdm", title="Wind Fleet Predictive Maintenance",
         description="Predict gearbox/pitch/yaw failures across the wind fleet from SCADA tags.",
         domain="Generation", sub_vertical="renewables", effort="L", win_rate=0.5, time_to_value="6–10 months",
         compliance=[], risk_tags=["equipment failure"],
         value_components=[_c("Turbine-downtime reduction", "generation fleet × capacity price × 365 ÷ 1M × 0.1%", 3.6e-7, ["generationFleetMW", "capacityPriceMWDay"])],
         requires=[("Data Historian", "Wind Turbine", "required"), ("EAM/APM", "Condition Monitoring / PdM", "required")],
         enables=[]),
    dict(id="x_gen_hydro_opt", title="Hydro Optimization & Scheduling",
         description="Optimize hydro dispatch against inflows, head and market prices.",
         domain="Generation", sub_vertical="hydro", effort="M", win_rate=0.55, time_to_value="6–9 months",
         compliance=["FERC"], risk_tags=["water availability"],
         value_components=[_c("Hydro revenue uplift", "generation fleet × capacity price × 365 ÷ 1M × 0.15%", 5.5e-7, ["generationFleetMW", "capacityPriceMWDay"])],
         requires=[("Data Historian", "Hydro Unit", "required"), ("Weather", "NWP Forecasts", "helpful"), ("Market/ISO Feed", "Day-Ahead LMP", "helpful")],
         enables=["x_mkt_bidding"]),
    dict(id="x_mkt_bidding", title="Market Bidding & Dispatch Optimization",
         description="Optimize unit bids and dispatch across ISO/RTO markets using forecasts + constraints.",
         domain="Generation", sub_vertical="cross", effort="L", win_rate=0.6, time_to_value="9–12 months",
         compliance=["FERC"], risk_tags=["price risk"],
         value_components=[_c("Gross-margin uplift", "annual fuel × 1.5%", 0.015, ["annualFuelSpendMM"]),
                           _c("Ancillary revenue", "generation fleet × capacity price × 365 ÷ 1M × 0.1%", 3.6e-7, ["generationFleetMW", "capacityPriceMWDay"])],
         requires=[("Market/ISO Feed", "Day-Ahead LMP", "required"), ("Market/ISO Feed", "Real-Time LMP", "required"), ("Market/ISO Feed", "Bids & Offers", "required"), ("EMS (Transmission)", "AGC / LFC", "helpful")],
         enables=["x_mkt_ftr"]),
    dict(id="x_mkt_ftr", title="FTR/CRR Congestion Hedging Analytics",
         description="Optimize FTR/CRR positions from congestion and settlement data.",
         domain="Regulatory", sub_vertical="cross", effort="M", win_rate=0.45, time_to_value="9–15 months",
         compliance=["FERC"], risk_tags=["price risk"],
         value_components=[_c("Congestion-cost hedge", "annual fuel × 0.4%", 0.004, ["annualFuelSpendMM"])],
         requires=[("Market/ISO Feed", "FTR / CRR", "required"), ("Market/ISO Feed", "Congestion / Constraints", "required"), ("Market/ISO Feed", "Settlements / Invoicing", "helpful")],
         enables=[]),
    dict(id="x_mkt_settlement", title="Settlement Shadow-Billing & Dispute Analytics",
         description="Recompute ISO settlements to catch discrepancies and recover revenue.",
         domain="Regulatory", sub_vertical="cross", effort="M", win_rate=0.5, time_to_value="6–10 months",
         compliance=["FERC"], risk_tags=["revenue leakage"],
         value_components=[_c("Settlement recovery", "annual revenue × 0.05%", 0.0005, ["annualRevenueMM"])],
         requires=[("Market/ISO Feed", "Settlements / Invoicing", "required"), ("Meter/AMI/MDM", "MDM Repository", "helpful"), ("Market/ISO Feed", "Real-Time LMP", "helpful")],
         enables=[]),
    dict(id="x_trans_rtca", title="Real-Time Contingency & Stability Assurance",
         description="Fuse RTCA with synchrophasor oscillation detection for proactive stability management.",
         domain="Transmission", sub_vertical="cross", effort="L", win_rate=0.52, time_to_value="9–15 months",
         compliance=["NERC"], risk_tags=["grid instability", "reliability"],
         value_components=[_c("Avoided reliability event ($M)", "T&D line miles × ~$8/mile", 8.0e-6, ["tdLineMiles"])],
         requires=[("EMS (Transmission)", "Real-Time Contingency Analysis", "required"), ("EMS (Transmission)", "State Estimation", "required"), ("PMU/Synchrophasor", "Oscillation Detection", "required")],
         enables=[]),
    dict(id="x_trans_dlr", title="Dynamic Line Rating Analytics",
         description="Compute dynamic thermal ratings from sensors + weather to unlock transmission capacity.",
         domain="Transmission", sub_vertical="cross", effort="M", win_rate=0.5, time_to_value="6–12 months",
         compliance=["NERC"], risk_tags=["congestion"],
         value_components=[_c("Congestion relief value", "transmission capex × 0.5%", 0.005, ["transmissionCapexMM"])],
         requires=[("Weather", "Icing / Wind Loading", "required"), ("EMS (Transmission)", "T-SCADA", "required"), ("PMU/Synchrophasor", "Phasor Measurement", "helpful")],
         enables=[]),
    dict(id="x_trans_xfmr", title="Transmission Transformer Thermal-Risk Analytics",
         description="Estimate transformer loss-of-life from online monitoring + DGA.",
         domain="Transmission", sub_vertical="cross", effort="M", win_rate=0.56, time_to_value="6–9 months",
         compliance=["NERC"], risk_tags=["equipment failure"],
         value_components=[_c("Transformer failure avoidance ($M)", "transformer count × replace cost, few units/yr", 6e-11, ["transformerCount", "transformerReplaceCost"], 0.5, 1.5)],
         requires=[("EAM/APM", "Condition Monitoring / PdM", "required"), ("EAM/APM", "Asset Performance & Health Scoring", "helpful")],
         enables=[]),
    dict(id="x_dist_flisr", title="FLISR Self-Healing Optimization",
         description="Tune FLISR schemes from OMS + power-flow to minimize customers interrupted.",
         domain="Distribution", sub_vertical="cross", effort="L", win_rate=0.6, time_to_value="9–12 months",
         compliance=["NERC"], risk_tags=["reliability"],
         value_components=[_c("SAIDI-driven value", "SAIDI value/min × current SAIDI × 4%", 0.04, ["saidiMinuteValueMM", "currentSAIDI"])],
         requires=[("ADMS (Distribution)", "FLISR", "required"), ("ADMS (Distribution)", "OMS (Outage Management)", "required"), ("ADMS (Distribution)", "Distribution Power Flow", "helpful"), ("GIS", "Electric Network Model / Connectivity", "required")],
         enables=["x_dist_storm"]),
    dict(id="x_dist_vvo", title="VVO/CVR Energy & Loss Optimization",
         description="Optimize volt/VAR + conservation voltage reduction to cut losses and peak demand.",
         domain="Distribution", sub_vertical="cross", effort="M", win_rate=0.58, time_to_value="6–10 months",
         compliance=[], risk_tags=["efficiency loss"],
         value_components=[_c("Loss + demand reduction", "distribution capex × 0.3%", 0.003, ["distributionCapexMM"])],
         requires=[("ADMS (Distribution)", "VVO / CVR", "required"), ("ADMS (Distribution)", "Distribution Power Flow", "required"), ("Meter/AMI/MDM", "Voltage / VAR Telemetry", "helpful")],
         enables=[]),
    dict(id="x_dist_storm", title="Storm Outage Prediction & Crew Pre-Staging",
         description="Predict weather-driven outages to pre-stage crews and cut restoration time.",
         domain="Distribution", sub_vertical="cross", effort="M", win_rate=0.55, time_to_value="6–9 months",
         compliance=[], risk_tags=["reliability"],
         value_components=[_c("Storm restoration savings", "avg storm cost × storms/yr × 8%", 0.08, ["avgStormCostMM", "stormsPerYear"])],
         requires=[("Weather", "Storm / Severe Weather Tracking", "required"), ("ADMS (Distribution)", "OMS (Outage Management)", "required"), ("GIS", "Vegetation Management", "helpful"), ("Weather", "Lightning Detection", "helpful")],
         enables=[]),
    dict(id="x_dist_der", title="DER Hosting-Capacity & VPP Orchestration",
         description="Aggregate and dispatch DERs for grid and market value via DERMS/VPP.",
         domain="Distribution", sub_vertical="renewables", effort="L", win_rate=0.5, time_to_value="9–15 months",
         compliance=["FERC"], risk_tags=["dispatch reliability"],
         value_components=[_c("Capacity value from DER", "generation fleet × capacity price × 365 ÷ 1M × 0.08%", 2.9e-7, ["generationFleetMW", "capacityPriceMWDay"])],
         requires=[("DERMS", "DER Dispatch & Control", "required"), ("DERMS", "Virtual Power Plant Orchestration", "required"), ("ADMS (Distribution)", "Distribution Power Flow", "helpful")],
         enables=["x_mkt_bidding"]),
    dict(id="x_dist_veg", title="Vegetation Risk & Trim Optimization",
         description="Prioritize vegetation trimming from LiDAR/imagery + outage history.",
         domain="Distribution", sub_vertical="cross", effort="M", win_rate=0.58, time_to_value="6–10 months",
         compliance=[], risk_tags=["reliability", "wildfire"],
         value_components=[_c("Trim-cost + outage reduction", "distribution capex × 0.25%", 0.0025, ["distributionCapexMM"])],
         requires=[("GIS", "Vegetation Management", "required"), ("ADMS (Distribution)", "OMS (Outage Management)", "helpful"), ("GIS", "Electric Network Model / Connectivity", "helpful")],
         enables=[]),
    dict(id="x_cust_theft", title="Revenue Protection / Energy-Theft Detection",
         description="Detect non-technical loss from AMI interval + VEE anomalies.",
         domain="Customer", sub_vertical="cross", effort="M", win_rate=0.6, time_to_value="4–8 months",
         compliance=[], risk_tags=["revenue leakage"],
         value_components=[_c("Recovered non-technical loss", "annual revenue × 0.15%", 0.0015, ["annualRevenueMM"])],
         requires=[("Meter/AMI/MDM", "Interval Usage Collection", "required"), ("Meter/AMI/MDM", "VEE (Validation/Estimation/Editing)", "required"), ("CIS/Billing", "Revenue Protection / Theft", "required")],
         enables=[]),
    dict(id="x_cust_churn", title="Customer Experience & Program Uptake",
         description="Predict satisfaction/churn and target DSM enrollment from CRM + usage.",
         domain="Customer", sub_vertical="cross", effort="M", win_rate=0.52, time_to_value="6–9 months",
         compliance=[], risk_tags=["churn"],
         value_components=[_c("Program uptake + retention ($M)", "customers × avg residential rev × ~0.06%", 5.56e-10, ["customerCount", "avgResidentialRevenue"], 0.5, 1.5)],
         requires=[("CIS/Billing", "CRM / Contact Center", "required"), ("Meter/AMI/MDM", "Load Profiles", "helpful"), ("CIS/Billing", "Programs / DSM Enrollment", "required")],
         enables=[]),
    dict(id="x_cust_baddebt", title="Collections & Bad-Debt Optimization",
         description="Prioritize collections and predict payment risk from billing + payments.",
         domain="Customer", sub_vertical="cross", effort="S", win_rate=0.55, time_to_value="4–6 months",
         compliance=[], risk_tags=["bad debt"],
         value_components=[_c("Bad-debt reduction", "annual revenue × bad-debt% ÷ 100 × 10%", 0.001, ["annualRevenueMM", "badDebtPct"], 0.5, 1.5)],
         requires=[("CIS/Billing", "Payments / Collections", "required"), ("CIS/Billing", "Billing Engine / Determinants", "helpful")],
         enables=[]),
    dict(id="x_reg_emissions", title="Emissions/CEMS Compliance Analytics",
         description="Monitor and predict emissions to prevent Part 75 exceedances and optimize allowances.",
         domain="Regulatory", sub_vertical="fossil", effort="M", win_rate=0.58, time_to_value="4–8 months",
         compliance=["EPA"], risk_tags=["emissions exceedance"],
         value_components=[_c("Penalty avoidance", "regulatory penalty risk × 20%", 0.2, ["regulatoryPenaltyRiskMM"])],
         requires=[("CEMS", "Gas Analyzers (NOx/SO2/CO2/O2)", "required"), ("CEMS", "DAHS (Data Acquisition)", "required"), ("CEMS", "Part 75 Reporting / EDR", "helpful")],
         enables=["x_reg_esg"]),
    dict(id="x_reg_esg", title="ESG & Emissions Reporting Automation",
         description="Automated ESG/emissions disclosure with audit-ready lineage.",
         domain="Regulatory", sub_vertical="cross", effort="M", win_rate=0.5, time_to_value="6–10 months",
         compliance=["EPA"], risk_tags=["reporting error"],
         value_components=[_c("Reporting-effort reduction", "O&M budget × 0.05%", 0.0005, ["omBudgetMM"])],
         requires=[("CEMS", "Part 75 Reporting / EDR", "required"), ("ERP", "Finance & Controlling", "helpful"), ("Document/Content Mgmt", "Commitment Tracking", "helpful")],
         enables=[]),
    dict(id="x_reg_ratecase", title="Rate-Case & Capital-Plan Analytics",
         description="Build rate-case evidence and optimize capital allocation from FICO + asset data.",
         domain="Regulatory", sub_vertical="cross", effort="L", win_rate=0.48, time_to_value="12–18 months",
         compliance=["FERC"], risk_tags=["cost recovery"],
         value_components=[_c("Rate-case prep + recovery", "rate case prep cost × 30%", 0.3, ["rateCasePrepCostMM"])],
         requires=[("Document/Content Mgmt", "Commitment Tracking", "required"), ("ERP", "Finance & Controlling", "required"), ("ERP", "Project System", "helpful")],
         enables=[]),
    dict(id="x_reg_nerc_cip", title="NERC CIP Compliance Monitoring",
         description="Track NERC CIP controls and evidence across OT cyber assets.",
         domain="Regulatory", sub_vertical="cross", effort="M", win_rate=0.5, time_to_value="9–12 months",
         compliance=["NERC"], risk_tags=["cyber", "compliance gap"],
         value_components=[_c("Audit-finding avoidance", "regulatory penalty risk × 10%", 0.1, ["regulatoryPenaltyRiskMM"])],
         requires=[("EMS (Transmission)", "T-SCADA", "helpful"), ("Document/Content Mgmt", "Records Management / Retention", "required")],
         enables=[]),
    dict(id="x_corp_docintel", title="Procedure & Regulatory Document Intelligence",
         description="LLM search/Q&A over procedures + NRC/FERC documents to cut engineer research time.",
         domain="Corporate Services", sub_vertical="nuclear", effort="M", win_rate=0.55, time_to_value="4–8 months",
         compliance=["NRC"], risk_tags=["compliance gap"],
         value_components=[_c("Engineer research-time savings ($M)", "workforce × engineer rate × ~1.2%", 1.2e-6, ["workforceSize", "engineerRate"], 0.5, 1.5)],
         requires=[("Document/Content Mgmt", "Regulatory Document Mgmt", "required"), ("Document/Content Mgmt", "Procedures Management", "required")],
         enables=[]),
    dict(id="x_corp_spares", title="Spare-Parts & Supply-Chain Optimization",
         description="Optimize spare-parts inventory and procurement using criticality and lead times.",
         domain="Corporate Services", sub_vertical="cross", effort="M", win_rate=0.56, time_to_value="6–9 months",
         compliance=[], risk_tags=["stockout"],
         value_components=[_c("Inventory carrying-cost reduction", "procurement spend × 0.8%", 0.008, ["procurementSpendMM"])],
         requires=[("ERP", "Materials Management", "required"), ("EAM/APM", "Spare Parts / Inventory", "required"), ("EAM/APM", "Asset Performance & Health Scoring", "helpful")],
         enables=[]),
    dict(id="x_corp_workforce", title="Workforce Planning & Attrition Prediction",
         description="Forecast attrition and certified-operator coverage from HCM data.",
         domain="Corporate Services", sub_vertical="cross", effort="M", win_rate=0.5, time_to_value="6–10 months",
         compliance=["NRC"], risk_tags=["staffing gap"],
         value_components=[_c("Attrition + overtime reduction", "workforce × replacement-cost($K) × retirement% ($M)", 1.0e-7, ["workforceSize", "avgReplacementCostK", "retirementEligiblePct"], 0.5, 1.5)],
         requires=[("ERP", "Human Capital Management", "required"), ("EAM/APM", "Scheduling & Crew Optimization", "helpful")],
         enables=[]),
    dict(id="x_corp_safety", title="Safety & OSHA Predictive Analytics",
         description="Predict and prevent recordable incidents from EHS + work data.",
         domain="Corporate Services", sub_vertical="cross", effort="M", win_rate=0.54, time_to_value="6–9 months",
         compliance=[], risk_tags=["safety"],
         value_components=[_c("Incident-cost avoidance ($M)", "OSHA cost($K) × recordables/yr × ~14%", 1.43e-4, ["oshaIncidentCostK", "oshaRecordablesPerYear"])],
         requires=[("ERP", "Environment, Health & Safety", "required"), ("EAM/APM", "Work Order Management", "helpful")],
         enables=[]),
    dict(id="x_corp_capital", title="Capital Project Cost & Schedule Risk",
         description="Forecast capital-project cost/schedule risk from PS + outage history.",
         domain="Corporate Services", sub_vertical="cross", effort="M", win_rate=0.5, time_to_value="9–12 months",
         compliance=[], risk_tags=["cost overrun"],
         value_components=[_c("Capital-overrun reduction", "capital budget × 0.3%", 0.003, ["capitalBudgetMM"])],
         requires=[("ERP", "Project System", "required"), ("ERP", "Finance & Controlling", "required")],
         enables=[]),
    dict(id="x_gen_fuel_hedge", title="Fuel Procurement & Hedging Analytics",
         description="Optimize fossil fuel procurement and hedging against forecasts and markets.",
         domain="Generation", sub_vertical="fossil", effort="M", win_rate=0.54, time_to_value="6–9 months",
         compliance=[], risk_tags=["price risk", "fuel supply"],
         value_components=[_c("Fuel-spend reduction", "annual fuel × 1%", 0.01, ["annualFuelSpendMM"])],
         requires=[("Fuel Management", "Fuel Contracts / Procurement", "required"), ("Fuel Management", "Gas Nominations", "helpful"), ("Market/ISO Feed", "Day-Ahead LMP", "helpful")],
         enables=[]),
    dict(id="x_gen_heatrate", title="Real-Time Heat-Rate & Thermal Performance",
         description="Live thermal-performance and heat-rate deviation monitoring across the fossil fleet.",
         domain="Generation", sub_vertical="fossil", effort="M", win_rate=0.6, time_to_value="4–8 months",
         compliance=["EPA"], risk_tags=["efficiency loss"],
         value_components=[_c("Heat-rate improvement", "annual fuel × 0.9%", 0.009, ["annualFuelSpendMM"])],
         requires=[("Data Historian", "Boiler / HRSG", "required"), ("Data Historian", "Steam Turbine", "helpful"), ("Data Historian", "Combustion / Burner Management", "required")],
         enables=["x_gen_turbine_dt", "x_reg_emissions"]),
    dict(id="x_gen_chemistry", title="Cycle Chemistry Optimization",
         description="Optimize water/cycle chemistry to reduce corrosion and chemistry-driven trips.",
         domain="Generation", sub_vertical="cross", effort="S", win_rate=0.55, time_to_value="4–6 months",
         compliance=[], risk_tags=["corrosion"],
         value_components=[_c("Chemistry-excursion reduction", "O&M budget × 0.08%", 0.0008, ["omBudgetMM"])],
         requires=[("LIMS", "Water / Fuel Chemistry", "required"), ("Data Historian", "Feedwater / Condensate", "helpful")],
         enables=[]),
    dict(id="x_trans_pmu_stability", title="Wide-Area Oscillation & Stability Monitoring",
         description="Detect inter-area oscillations and stability risks from synchrophasor data.",
         domain="Transmission", sub_vertical="cross", effort="M", win_rate=0.5, time_to_value="6–12 months",
         compliance=["NERC"], risk_tags=["grid instability"],
         value_components=[_c("Reliability-event avoidance ($M)", "T&D line miles × ~$6/mile", 6.0e-6, ["tdLineMiles"])],
         requires=[("PMU/Synchrophasor", "Phasor Measurement", "required"), ("PMU/Synchrophasor", "Oscillation Detection", "required"), ("PMU/Synchrophasor", "Phasor Data Concentrator", "helpful")],
         enables=["x_trans_rtca"]),
    dict(id="x_dist_dsse", title="Distribution State Estimation & Observability",
         description="Estimate unmeasured feeder states from AMI + SCADA for better ops.",
         domain="Distribution", sub_vertical="cross", effort="M", win_rate=0.5, time_to_value="6–10 months",
         compliance=[], risk_tags=["observability"],
         value_components=[_c("Ops-efficiency value", "distribution capex × 0.15%", 0.0015, ["distributionCapexMM"])],
         requires=[("ADMS (Distribution)", "Distribution State Estimation", "required"), ("Meter/AMI/MDM", "Interval Usage Collection", "required"), ("ADMS (Distribution)", "D-SCADA", "helpful")],
         enables=["x_dist_vvo", "x_dist_der"]),
    dict(id="x_gen_agc_perf", title="AGC Regulation Performance & Mileage",
         description="Monitor automatic-generation-control regulation performance and mileage payments.",
         domain="Generation", sub_vertical="cross", effort="S", win_rate=0.55, time_to_value="4–6 months",
         compliance=["NERC"], risk_tags=["performance penalty"],
         value_components=[_c("Regulation revenue", "generation fleet × capacity price × 365 ÷ 1M × 0.05%", 1.8e-7, ["generationFleetMW", "capacityPriceMWDay"])],
         requires=[("EMS (Transmission)", "AGC / LFC", "required"), ("Market/ISO Feed", "Ancillary Services", "helpful")],
         enables=[]),
    dict(id="x_nuc_core_opt", title="Nuclear Fuel-Cycle & Core-Loading Optimization",
         description="Optimize core loading, burnup and enrichment to extend cycles and cut fuel cost.",
         domain="Generation", sub_vertical="nuclear", effort="L", win_rate=0.5, time_to_value="12–18 months",
         compliance=["NRC"], risk_tags=["fuel supply"],
         value_components=[_c("Fuel-cost reduction", "annual fuel × 2%", 0.02, ["annualFuelSpendMM"])],
         requires=[("Fuel Management", "Core Design / Reload", "required"), ("Fuel Management", "Nuclear Fuel Cycle", "required"), ("Data Historian", "Reactor Core / Neutronics", "helpful")],
         enables=["x_nuc_refuel_opt"]),
    dict(id="x_corp_apm_dash", title="Enterprise APM Reliability Dashboard",
         description="Executive asset-performance dashboard unifying PdM signals across the fleet.",
         domain="Corporate Services", sub_vertical="cross", effort="M", win_rate=0.62, time_to_value="6–9 months",
         compliance=["NERC"], risk_tags=["equipment failure"],
         value_components=[_c("Unplanned-maintenance reduction", "O&M budget × 0.2%", 0.002, ["omBudgetMM"])],
         requires=[("EAM/APM", "Asset Performance & Health Scoring", "required"), ("EAM/APM", "Condition Monitoring / PdM", "helpful"), ("EAM/APM", "Reliability / RCM", "helpful")],
         enables=[]),
]
