"""Rebrand the PRODUCT name inside the committed SPA bundle.

The React source for this bundle is not in the repo (see README), so the product
name can only be corrected by patching the built assets. That is safe here because
every replacement is a whole user-visible STRING LITERAL — no identifiers, class
names, or minified symbols are touched, and each pattern is asserted to appear the
expected number of times before anything is written.

CAREFUL DISTINCTION: "Value Flywheel" is BOTH the old product name AND the name of
a real feature (the Flywheel tab, the blast-radius view). Only product-name uses
are rebranded; the feature keeps its name.
"""
import glob
import os
import sys

ASSETS = "frontend/dist/assets"
INDEX = "frontend/dist/index.html"

# (pattern, replacement, why) — product-name contexts only.
RULES = [
    ("Value Flywheel · Powered by Databricks · P&U Data & AI portfolio",
     "Grid Atlas · Powered by Databricks · P&U Data & AI catalog",
     "app footer"),
    ("Generated by Value Flywheel · Powered by Databricks",
     "Generated by Grid Atlas · Powered by Databricks",
     "exported one-pager credit"),
    ("Value Flywheel — Terms of Use",
     "Grid Atlas — Terms of Use",
     "terms modal title"),
    ("Data & AI Value Flywheel",
     "Data & AI Roadmap",
     "roadmap page H1 (was the product name, not the flywheel feature)"),
]

# Left ALONE deliberately — these name the FEATURE, not the product:
KEEP = [
    'label:"Value Flywheel"',                    # nav tab
    "Value Flywheel — Blast Radius by LOB",      # blast-radius header
    "unlocks on the Value Flywheel",             # onboarding copy
]


def main():
    if not os.path.isdir(ASSETS):
        sys.exit(f"missing {ASSETS}")
    files = sorted(glob.glob(f"{ASSETS}/*.js")) + sorted(glob.glob(f"{ASSETS}/*.css")) + [INDEX]

    total = 0
    for pattern, replacement, why in RULES:
        hits = 0
        for path in files:
            if not os.path.exists(path):
                continue
            text = open(path, encoding="utf-8", errors="surrogateescape").read()
            if pattern not in text:
                continue
            count = text.count(pattern)
            open(path, "w", encoding="utf-8", errors="surrogateescape").write(
                text.replace(pattern, replacement))
            hits += count
        print(f"  {hits:2d}x  {why}")
        total += hits
        if hits == 0:
            print(f"        WARNING: pattern not found: {pattern!r}")

    print(f"\n  {total} product-name strings rebranded")
    print("  feature names preserved:")
    for keep in KEEP:
        found = sum(open(p, encoding='utf-8', errors='surrogateescape').read().count(keep)
                    for p in files if os.path.exists(p))
        print(f"    {found}x  {keep[:52]}")


if __name__ == "__main__":
    main()
