"""Rebrand the PRODUCT name inside the committed SPA bundle.

The React source for this bundle is not in the repo (see README), so the product
name can only be corrected by patching the built assets. That is safe here because
every replacement is a whole user-visible STRING LITERAL — no identifiers, class
names, or minified symbols are touched, and each pattern is asserted to appear the
expected number of times before anything is written.

CAREFUL DISTINCTION: "Value Flywheel" is BOTH a product name AND the name of a real
feature (the Flywheel tab, the blast-radius view). Only product-name uses are
rebranded; the feature keeps its name.

NAME HISTORY, because the rules below only make sense with it:
    "Value Flywheel"  (original)  ->  "Grid Atlas"  ->  "AI Value Flywheel"
The current product name is AI VALUE FLYWHEEL. Every rule is therefore idempotent by
construction: each maps some earlier name to the current one, so running this on an
already-branded bundle is a no-op rather than producing "AI AI Value Flywheel".
"""
import glob
import os
import sys

ASSETS = "frontend/dist/assets"
INDEX = "frontend/dist/index.html"

# (pattern, replacement, why) — product-name contexts only.
RULES = [
    # --- from the ORIGINAL "Value Flywheel" name ---------------------------
    ("Value Flywheel · Powered by Databricks · P&U Data & AI portfolio",
     "AI Value Flywheel · Powered by Databricks · P&U Data & AI catalog",
     "app footer (from the original name)"),
    ("Data & AI Value Flywheel",
     "Data & AI Roadmap",
     "roadmap page H1 (was the product name, not the flywheel feature)"),

    # --- from the interim "Grid Atlas" name --------------------------------
    # Ordered so the longest, most specific string is replaced first: a bare
    # "Grid Atlas" rule running earlier would consume the substring and leave the
    # surrounding text unrebranded.
    ("Grid Atlas · Powered by Databricks · P&U Data & AI catalog",
     "AI Value Flywheel · Powered by Databricks · P&U Data & AI catalog",
     "app footer"),
    ("Grid Atlas · Powered by Databricks",
     "AI Value Flywheel · Powered by Databricks",
     "footer / export credit"),
    ("Generated by Grid Atlas · Powered by Databricks",
     "Generated by AI Value Flywheel · Powered by Databricks",
     "exported one-pager credit"),
    ("Grid Atlas — Terms of Use",
     "AI Value Flywheel — Terms of Use",
     "terms modal title"),
    ("Grid Atlas — P&amp;U Data &amp; AI Catalog",
     "AI Value Flywheel — P&amp;U Data &amp; AI Catalog",
     "page <title>"),
    # The header wordmark renders as two spans: "Grid" + a coloured "Atlas".
    # Rewritten to "AI Value" + "Flywheel" so the accent still lands on the second
    # word, which is what makes the wordmark read as one mark rather than two words.
    ('children:["Grid ",a.jsx("span",{style:{color:"#FF3621"},children:"Atlas"})]',
     'children:["AI Value ",a.jsx("span",{style:{color:"#FF3621"},children:"Flywheel"})]',
     "header wordmark"),
    # Any remaining prose mention. Last, so the specific rules above win.
    ("Grid Atlas", "AI Value Flywheel", "remaining prose mentions"),
]

# Left ALONE deliberately — these name the FEATURE, not the product:
KEEP = [
    'label:"Value Flywheel"',                    # nav tab
    "Value Flywheel — Blast Radius by LOB",      # blast-radius header
    "unlocks on the Value Flywheel",             # onboarding copy
]


def main():
    if not os.path.isdir(ASSETS):
        sys.exit(f"missing {ASSETS}")
    files = sorted(glob.glob(f"{ASSETS}/*.js")) + sorted(glob.glob(f"{ASSETS}/*.css")) + [INDEX]

    total = 0
    for pattern, replacement, why in RULES:
        hits = 0
        for path in files:
            if not os.path.exists(path):
                continue
            text = open(path, encoding="utf-8", errors="surrogateescape").read()
            if pattern not in text:
                continue
            count = text.count(pattern)
            open(path, "w", encoding="utf-8", errors="surrogateescape").write(
                text.replace(pattern, replacement))
            hits += count
        print(f"  {hits:2d}x  {why}")
        total += hits
        if hits == 0:
            # Not an error: most rules target a SUPERSEDED name, so a bundle that
            # never carried that name — or has already been rebranded — legitimately
            # matches nothing.
            print(f"        (absent — already rebranded, or never carried "
                  f"{pattern[:40]!r})")

    print(f"\n  {total} product-name strings rebranded")
    print("  feature names preserved:")
    for keep in KEEP:
        found = sum(open(p, encoding='utf-8', errors='surrogateescape').read().count(keep)
                    for p in files if os.path.exists(p))
        print(f"    {found}x  {keep[:52]}")


if __name__ == "__main__":
    main()
